import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "surface-container-high": "#eae8e7",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#011e2d",
        "on-surface": "#1b1c1c",
        "tertiary-fixed-dim": "#cec5ba",
        "surface-tint": "#82533f",
        "primary-fixed-dim": "#f6b9a0",
        "surface-bright": "#fbf9f8",
        secondary: "#486173",
        "on-secondary-container": "#4d6677",
        "inverse-on-surface": "#f2f0f0",
        "on-secondary-fixed-variant": "#304a5a",
        "secondary-container": "#c9e3f8",
        "on-primary-fixed-variant": "#663c29",
        "error-container": "#ffdad6",
        "surface-container": "#efeded",
        "inverse-surface": "#303030",
        "primary-fixed": "#ffdbcd",
        "inverse-primary": "#f6b9a0",
        "tertiary-fixed": "#ebe1d6",
        "surface-variant": "#e4e2e2",
        tertiary: "#645d55",
        "on-background": "#1b1c1c",
        "on-primary-container": "#4f2817",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dbd9d9",
        "on-tertiary-container": "#37332b",
        "tertiary-container": "#a29a90",
        "surface-container-highest": "#e4e2e2",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#4c463e",
        surface: "#fbf9f8",
        "on-error": "#ffffff",
        "surface-container-low": "#f5f3f3",
        outline: "#84746e",
        "on-primary-fixed": "#321204",
        "secondary-fixed": "#cbe6fa",
        "outline-variant": "#d6c2bb",
        "on-tertiary-fixed": "#1f1b14",
        "on-surface-variant": "#51443f",
        "secondary-fixed-dim": "#b0cade",
        error: "#ba1a1a",
        "primary-container": "#c68e77",
        primary: "#82533f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "80px",
        margin: "32px",
        "container-max": "1120px",
        unit: "8px",
        gutter: "24px",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        signika: ["Signika", "sans-serif"],
        geist: ["var(--font-geist-sans)"],
        "geist-mono": ["var(--font-geist-mono)"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.3", fontWeight: "500" },
        ],
        display: [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "300" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.4", fontWeight: "500" },
        ],
      },
      boxShadow: {
        "soft-depth": "0 10px 40px -15px rgba(130, 83, 63, 0.08)",
      },
      keyframes: {
        loading: {
          "0%": { transform: "translateX(-100%)" },
          "50%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(-100%)" },
        },
      },
    },
  },
  plugins: [typography],
} satisfies Config;
