import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="bg-gray-800 py-6 text-white text-center">
          <div className="max-w-6xl mx-auto">
            <p className="text-sm">
              &copy; {new Date().getFullYear()} Declutter.zen. All rights
              reserved.
            </p>
            <p className="text-sm mt-2">
              Built with love to help you simplify your life.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
